# .goreleaser.yml
version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: firstclick
    main: ./cmd/firstclick       
    binary: firstclick
    env:
      - CGO_ENABLED=0             
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w                     
      - -X main.version={{.Version}}  

archives:
  - id: firstclick-archive
    format: tar.gz               
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"  

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"

release:
  github:
    owner: sachinggsingh 
    name: sachinggsingh/FirstClick
  draft: false
  prerelease: auto