apiVersion: v1
kind: Pod
metadata:
  name: firstclick
  labels:
    app.kubernetes.io/name: firstclick
spec:
  containers:
  - name: firstclick
    image: sachinggsingh/firstclick
    ports:
    - containerPort: 80
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
      requests:
        memory: "128Mi"
        cpu: "500m"
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000
      runAsGroup: 1000
      capailities:
        drop:
          - ALL   
    readinessProbe:
      httpGet:
        path: /health
        port: 80
      initialDelaySeconds: 15
      periodSeconds: 10
    livenessProbe:
      httpGet:
        path: /health
        port: 80
      initialDelaySeconds: 15
      periodSeconds: 10

    
