apiVersion: apps/v1
kind: Deployment
metadata:
  name: firstclick
  labels:
    app: firstclick-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: firstclick
  template:
    metadata:
      labels:
        app: firstclick
    spec:
      containers:
      - name: firstclick
        image: sachinggsingh/firstclick
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: firstclick-configmap
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "500m"
