apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data
  namespace: firstclick
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
